services:
  postgres:
    image: postgres:15
    container_name: url-shortener-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: urlshortener
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  link-service:
    build:
      context: .
      dockerfile: services/link-service/Dockerfile
    container_name: link-service
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: urlshortener
      SERVICE_PORT: 8001
    ports:
      - "8001:8001"

  redirect-service:
    build:
      context: .
      dockerfile: services/redirect-service/Dockerfile
    container_name: redirect-service
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: urlshortener
      SERVICE_PORT: 8002
    ports:
      - "8002:8002"

  stats-service:
    build:
      context: .
      dockerfile: services/stats-service/Dockerfile
    container_name: stats-service
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: urlshortener
      SERVICE_PORT: 8003
    ports:
      - "8003:8003"

  gateway:
    image: nginx:alpine
    container_name: url-shortener-gateway
    volumes:
      - ./local-gateway.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - link-service
      - redirect-service
      - stats-service
    ports:
      - "8080:8080"

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    container_name: url-shortener-frontend
    ports:
      - "3000:80"
    depends_on:
      - gateway

volumes:
  pgdata:
